import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>This is a next js Api example with postgres as the database</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Semusi project</a>
        </h1>

        <p className={styles.description}>
          Just run the code and test it on postman
         
        </p>

        
         
      </main>

     
    </div>
  )
}
